// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exams.entity;

import com.exams.entity.Exam;
import com.exams.entity.ExamDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ExamDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExamDataOnDemand: @Component;
    
    private Random ExamDataOnDemand.rnd = new SecureRandom();
    
    private List<Exam> ExamDataOnDemand.data;
    
    public Exam ExamDataOnDemand.getNewTransientExam(int index) {
        Exam obj = new Exam();
        setDescription(obj, index);
        return obj;
    }
    
    public void ExamDataOnDemand.setDescription(Exam obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public Exam ExamDataOnDemand.getSpecificExam(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Exam obj = data.get(index);
        Long id = obj.getId();
        return Exam.findExam(id);
    }
    
    public Exam ExamDataOnDemand.getRandomExam() {
        init();
        Exam obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Exam.findExam(id);
    }
    
    public boolean ExamDataOnDemand.modifyExam(Exam obj) {
        return false;
    }
    
    public void ExamDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Exam.findExamEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Exam' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Exam>();
        for (int i = 0; i < 10; i++) {
            Exam obj = getNewTransientExam(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
