// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exams.entity;

import com.exams.entity.QuestionOption;
import com.exams.entity.QuestionOptionDataOnDemand;
import com.exams.entity.QuestionOptionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuestionOptionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuestionOptionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuestionOptionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuestionOptionIntegrationTest: @Transactional;
    
    @Autowired
    QuestionOptionDataOnDemand QuestionOptionIntegrationTest.dod;
    
    @Test
    public void QuestionOptionIntegrationTest.testCountQuestionOptions() {
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", dod.getRandomQuestionOption());
        long count = QuestionOption.countQuestionOptions();
        Assert.assertTrue("Counter for 'QuestionOption' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testFindQuestionOption() {
        QuestionOption obj = dod.getRandomQuestionOption();
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide an identifier", id);
        obj = QuestionOption.findQuestionOption(id);
        Assert.assertNotNull("Find method for 'QuestionOption' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QuestionOption' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testFindAllQuestionOptions() {
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", dod.getRandomQuestionOption());
        long count = QuestionOption.countQuestionOptions();
        Assert.assertTrue("Too expensive to perform a find all test for 'QuestionOption', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QuestionOption> result = QuestionOption.findAllQuestionOptions();
        Assert.assertNotNull("Find all method for 'QuestionOption' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QuestionOption' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testFindQuestionOptionEntries() {
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", dod.getRandomQuestionOption());
        long count = QuestionOption.countQuestionOptions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QuestionOption> result = QuestionOption.findQuestionOptionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QuestionOption' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QuestionOption' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testFlush() {
        QuestionOption obj = dod.getRandomQuestionOption();
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide an identifier", id);
        obj = QuestionOption.findQuestionOption(id);
        Assert.assertNotNull("Find method for 'QuestionOption' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuestionOption(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QuestionOption' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testMergeUpdate() {
        QuestionOption obj = dod.getRandomQuestionOption();
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide an identifier", id);
        obj = QuestionOption.findQuestionOption(id);
        boolean modified =  dod.modifyQuestionOption(obj);
        Integer currentVersion = obj.getVersion();
        QuestionOption merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QuestionOption' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", dod.getRandomQuestionOption());
        QuestionOption obj = dod.getNewTransientQuestionOption(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QuestionOption' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'QuestionOption' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testRemove() {
        QuestionOption obj = dod.getRandomQuestionOption();
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide an identifier", id);
        obj = QuestionOption.findQuestionOption(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QuestionOption' with identifier '" + id + "'", QuestionOption.findQuestionOption(id));
    }
    
}
