// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exams.entity;

import com.exams.entity.QuestionOption;
import com.exams.entity.QuestionOptionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect QuestionOptionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: QuestionOptionDataOnDemand: @Component;
    
    private Random QuestionOptionDataOnDemand.rnd = new SecureRandom();
    
    private List<QuestionOption> QuestionOptionDataOnDemand.data;
    
    public QuestionOption QuestionOptionDataOnDemand.getNewTransientQuestionOption(int index) {
        QuestionOption obj = new QuestionOption();
        setDescription(obj, index);
        setOptionNumber(obj, index);
        return obj;
    }
    
    public void QuestionOptionDataOnDemand.setDescription(QuestionOption obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void QuestionOptionDataOnDemand.setOptionNumber(QuestionOption obj, int index) {
        String optionNumber = "optionNumber_" + index;
        obj.setOptionNumber(optionNumber);
    }
    
    public QuestionOption QuestionOptionDataOnDemand.getSpecificQuestionOption(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        QuestionOption obj = data.get(index);
        Long id = obj.getId();
        return QuestionOption.findQuestionOption(id);
    }
    
    public QuestionOption QuestionOptionDataOnDemand.getRandomQuestionOption() {
        init();
        QuestionOption obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return QuestionOption.findQuestionOption(id);
    }
    
    public boolean QuestionOptionDataOnDemand.modifyQuestionOption(QuestionOption obj) {
        return false;
    }
    
    public void QuestionOptionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = QuestionOption.findQuestionOptionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'QuestionOption' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<QuestionOption>();
        for (int i = 0; i < 10; i++) {
            QuestionOption obj = getNewTransientQuestionOption(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
