// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exams.entity;

import com.exams.entity.Exam;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Exam_Roo_Configurable {
    
    declare @type: Exam: @Configurable;
    
}
