// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exams.entity;

import com.exams.entity.HelloWorldEntity;

privileged aspect HelloWorldEntity_Roo_JavaBean {
    
    public String HelloWorldEntity.getHello() {
        return this.hello;
    }
    
    public void HelloWorldEntity.setHello(String hello) {
        this.hello = hello;
    }
    
}
